[package]
name = 'rsquid'
version = '0.0.1'
edition = '2021'

[lib]
crate-type = [ 'staticlib' ]
name = 'rsquid'

[dependencies]
extendr-api = '*'
anyhow = "*"

serde = "*"
serde_yaml = "*"

named_pipe = "0.4.1"
winapi = { version = "0.3.9", features = ["winbase"] }
kernel32-sys = "0.2.2"

